version: 2.1
orbs:
  ruby: circleci/ruby@2.3.1

jobs:
  hello-ruby:
    executor:
      name: ruby/default
      tag: '3.3.6'

    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: "Show ruby version"
          command: ruby --version
      - run:
          name: "Which ruby"
          command: which ruby
      - run:
          name: "Show rails version"
          command: ~/project/bin/rails --version
      - run:
          name: "rubocop"
          command: ~/project/bin/rubocop

workflows:
  say-hello-workflow:
    jobs:
      - hello-ruby
