version: 2.1
orbs:
  ruby: circleci/ruby@2.3.1

jobs:
  prepare_ruby:
    executor:
      name: ruby/default
      tag: '3.3.6'
    steps:
      - checkout
      - ruby/install-deps
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  checking_env:
    executor:
      name: ruby/default
      tag: '3.3.6'
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: "Show ruby version"
          command: ruby --version
      - run:
          name: "Which ruby"
          command: which ruby
      - run:
          name: "Checking OpenSSL"
          command: which openssl
      - run:
          name: "Checking OpenSSL version"
          command: openssl version
      - run:
          name: "Show rails version"
          command: ~/project/bin/rails --version

  run_rubocop:
    executor:
      name: ruby/default
      tag: '3.3.6'
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: "checking current dir"
          command: pwd
      - run:
          name: "checking Rubocop version"
          command: bundle exec rubocop -v
      - run:
          name: "Run rubocop"
          command: bundle exec rubocop
      # - ruby/rubocop-check

workflows:
  build_and_test:
    jobs:
      - prepare_ruby
      - checking_env:
          requires:
            - prepare_ruby
      - run_rubocop:
          requires:
            - prepare_ruby
